apiVersion: v1
kind: Service

metadata:
  name: common-api-svc
  namespace: common
spec:
  selector:
    app: common-api
  
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: http
    #nodePort: 30001
  #type: NodePort
  


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api
  namespace: common
  labels:
    app: common-api
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: common-api
      
  template:
    metadata:
      labels:
        app: common-api
    spec:
      containers:
      - name: common-api
        image: common-api
        imagePullPolicy: Never        
        ports:
        - name: http
          containerPort: 9002
        volumeMounts:   
        - name: log-volume
          mountPath: /logs
          
      - name: fluent-bit
        image: fluent/fluent-bit
        volumeMounts:   
        - name: log-volume
          mountPath: /logs   
        - name: config  
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/parsers_springboot.conf
          subPath: parsers_springboot.conf
      volumes:
      - name: log-volume
        emptyDir: {}     
      - name: config
        configMap:
          name: fluent-bit-config